Section "InputClass"
    Identifier "Touchpad (synaptics custom)"
    MatchProduct "DELL0819:00"
    MatchDevicePath "/dev/input/event*"
    Driver "synaptics"
    Option "TapAndDragGesture" "0"
    Option "CoastingSpeed" "0"
    Option "PalmDetect" "0"
    Option "CircularScrolling" "0"
    Option "TapButton3" "0"
    Option "TapButton2" "0"
    Option "TapButton1" "0"
    Option "LBCornerButton" "0"
    Option "LTCornerButton" "0"
    Option "RBCornerButton" "0"
    Option "RTCornerButton" "0"
    Option "LockedDrags" "0"
    Option "HorizTwoFingerScroll" "0"
    Option "CornerCoasting" "0"
    Option "HorizEdgeScroll" "0"
    Option "VertEdgeScroll" "0"
EndSection

# End