Section "Module"
   Load "dri3"
EndSection

Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"

   # Required by Google Earth, other modern GL apps:
   Option      "DRI"   "3"

   # Fixes screen tearing:
   Option      "TripleBuffer" "true"
   Option      "TearFree"     "true"
EndSection
